### ISSUE TITLE
Encrypt hook: wait forever for device with keyfile until ENTER is pressed (or device is inserted)

### ISSUE THREAD

**Issue by benruijl** [falconindy/mkinitcpio#2]
In the current setup, the encrypt hook waits a certain amount of time (10 by default) for the device with the keyfile to be inserted. After, it falls back to the passphrase mode.

This behaviour is not ideal in the following 2 cases:
1) the device is not at hand in ten seconds, so the system has to be rebooted to use the keyfile
2) the device is not at hand at all, and the user has to wait 10 seconds to enter the password

I think more useful behaviour is that the program waits forever for the keyfile, until the ENTER key is pressed (or the device is inserted).

Adding the following line to the `while` loop in `poll_device` enables the enter key:
`read -t 0 -r && { read -r; break; }`

and modifying the wait time to a large number in the encrypt hook would be a quick patch for my suggestion. However, the `poll_device` is also used for other hooks, where this modification may be unwanted . Therefore, it may be better to add an extra parameter to the function.

Since I don't have an overview of the complete mkinitcpio, I don't know what is best. Could you have a look at this?

**Comment by falconindy** [comment]
You could also implement a wait_for_device function which wraps poll_device (and wouldn't require changes to mkinitcpio proper). But, better yet, use the sd_encrypt hook with systemd where you can set an infinite device timeout.

**Comment by benruijl** [comment]
Thanks! If I use sd_encrypt, do I still have to add the feature somewhere that I can stop the wait and enter the password straight away?

**Comment by falconindy** [comment]
No. You enter the password when the device shows up.

**Comment by benruijl** [comment]
Maybe I misunderstand, but in my setup I either unlock root with a key file
or with a password (not the password for the key file). So I would like to
be able to enter the password without the key file device showing up, and
without waiting for the device.

**Comment by falconindy** [comment]
Oh, I see. You'd want to to file a bug against cryptsetup and/or systemd (upstream) then for this feature. Mkinitcpio isnt going to do what you want (and this isn't the right tracker).

**Comment by benruijl** [comment]
At the moment the encrypt hook first tries to read the key file, and if
that doesn't work, it tries to unlock root with a password. This is exactly
my use case.

The thing that is sub optimal in my opinion is that in the current version
you have to put the device in within a certain amount of time, or wait for
that amount of time to enter the password. I would prefer an infinite wait
time that can be canceled by pressing enter. Alternatively, I could write
my own hook if people prefer the current behavior.
