### ISSUE TITLE
How to create a (very) early hook

### ISSUE THREAD

**Issue by mickpf** [falconindy/mkinitcpio#3]
Hallo Dave,

sorry to contact you in this way...

I NEED a (very) early hook in mkinitcpio to include few ACPI upgrade files in the 'initramfs.img'.
I don't have any idea how to do that. I don't know how to write a well formed script for this solution.
Entering something like this:
FILES="...."
 in '/etc/mkinitcpio.conf' doesn't solve the problem: The kernel don't find these files.

Thanks in advance
Michael

**Comment by falconindy** [comment]
How early? what does the script need to do? Note that we dropped support from mkinitcpio years ago for updating the DSDT because it simply doesn't work.
